[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2@^1.6.2
    bblanchon/ArduinoJson@^7.3.0
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit GFX Library@^1.11.11
build_flags =
    -DMQTT_MAX_PACKET_SIZE=4096
    -DCORE_DEBUG_LEVEL=3
